# Generated by Django 2.0.4 on 2019-09-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachername', models.CharField(max_length=100)),
                ('loginname', models.CharField(max_length=100)),
                ('desc', models.CharField(blank=True, max_length=1000, null=True)),
                ('display_idx', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'main_teacher',
            },
        ),
    ]
