# Generated by Django 2.0.4 on 2019-09-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='selected',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
