# Generated by Django 2.0.4 on 2019-09-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_teacher_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='selected',
            field=models.CharField(max_length=100),
        ),
    ]
