# Generated by Django 2.0.4 on 2019-09-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190927_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='selected',
        ),
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(related_name='course_teacher', to='main.Course'),
        ),
    ]
